// admin-client/src/components/AppTopBar.tsx
import { ReactNode } from "react";
import { HEADER_SIZE } from "../consts";
import { AppIcon } from "./AppIcon";

interface AppTopBarProps {
  children?: ReactNode;
  title: string;
}

export function AppTopBar({ children, title }: AppTopBarProps) {
  return (
    <>
      <div style={{ height: HEADER_SIZE }} />
      <header
        style={{ height: HEADER_SIZE }}
        className="fixed top-0 left-0 right-0 bg-white px-6 flex items-center justify-between"
      >
        <div className="flex items-center">
          <div className="ml-2 w-[256px]">
            <h6 className="text-xl font-normal">Srpski reć</h6>
            <div className="flex items-center">
              <AppIcon size="18px" name="admin_panel_settings" />
              <span className="ml-2 text-sm text-gray-700">Admin</span>
            </div>
          </div>
          <h1 className="text-2xl">{title}</h1>
        </div>

        <div>{children}</div>
      </header>
    </>
  );
}

// dashboard/src/components/AppTopBar.vue
<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
	name: "AppTopBar",
	data() {
		return {};
	},
});

</script>

<template>
	<header
		class="bg-red full-width q-px-md flex justify-between items-center"
	>
		<div class="flex items-center">
			<div class="q-ml-xs left-container">
				<h6 class="text-h6">
					Srpski reć
				</h6>
				<div class="flex items-center">
					<!-- <Icon
						name="admin_panel_settings"
						color="black"
						size="20px"
					/> -->
					<span class="text-subtitle2 text-grey-7">Admin</span>
				</div>
			</div>
			<h4 class="text-h4">
				Words
			</h4>
		</div>

		<div>test test</div>
	</header>
</template>

<style lang="scss" scoped>

.left-container {
  width: 212px;
}

</style>
